language: python
python:
  - "3.6"
# command to install dependencies
branches:
    only:
        - develop
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest

script:
  - nosetests --with-coverage  --cover-package=app && coverage report



after_success: 
  - coveralls
